name: Take Screenshot and Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight, adjust as needed

jobs:
  build-and-screenshot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: '1.69' # Use the version you need

    - name: Install dependencies
      run: cargo build --release

    - name: Install screenshot tool
      run: sudo apt-get install -y x11-apps imagemagick

    - name: Run GUI app and take screenshot
      run: |
        nohup cargo run --release &
        sleep 10 # Give the app some time to start
        import -window root assets/screenshot.png # Adjust the command to capture the GUI window as needed

    - name: Check updated files
      run: |
        ls -l assets
        cat assets/screenshot.png
        cat README.md

    - name: Update README with the new screenshot
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        
        # Ensure the assets directory exists
        mkdir -p assets
        
        # Remove old screenshot if it exists
        if grep -q 'screenshot.png' README.md; then
          sed -i '/^!.*screenshot.png$/d' README.md
        fi

        # Add new screenshot
        echo '![App Screenshot](assets/screenshot.png)' >> README.md
        
        # Check the README file to ensure changes
        cat README.md
        
        # Commit and push changes
        git add README.md
        git status
        git diff --cached
        git commit -m 'Update README with new screenshot'
        git push
